# Generated by Django 4.1.7 on 2023-03-12 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='phot',
            new_name='photo',
        ),
    ]
